<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="arm_base_length" value="0.1"/>
    <xacro:property name="arm_base_width" value="0.1"/>
    <xacro:property name="arm_base_height" value="0.02"/>
    <xacro:property name="arm_base_mass" value="0.5"/>

    <xacro:property name="arm_torso_radius" value="0.02"/>
    <xacro:property name="arm_torso_length" value="0.3"/>
    <xacro:property name="arm_torso_mass" value="0.3"/>

    <xacro:macro name="arm_module" params="parent_link ox oz">
        <link name="arm_base_link">
            <visual>
                <geometry>
                    <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
                </geometry>
                <material name="orange" />
                <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
                </geometry>
                <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
            </collision>
            <xacro:box_inertia m="${arm_base_mass}" l="${2*arm_base_length}" w="${2*arm_base_width}" h="${2*arm_base_height}"
                                xyz="0 0 ${arm_base_height/2}" rpy="0 0 0" />
        </link>


        <xacro:macro name="arm_link" params="prefix color">
            <link name="${prefix}_link">
                <visual>
                    <geometry>
                        <cylinder radius="${arm_torso_radius}" length="${arm_torso_length}"/>
                    </geometry>
                    <origin xyz="0 0 ${arm_torso_length/2}" rpy="0 0 0"/>
                    <material name="${color}"/>
                </visual>
                <collision>
                    <geometry>
                        <cylinder radius="${arm_torso_radius}" length="${arm_torso_length}"/>
                    </geometry>
                    <origin xyz="0 0 ${arm_torso_length/2}" rpy="0 0 0"/>
                </collision>
                <xacro:cylinder_inertia m="${arm_torso_mass}" r="${2*arm_torso_radius}" h="${2*arm_torso_length}" 
                                xyz="0 0 ${arm_torso_length/2}" rpy="0 0 0"/>
            </link>
        </xacro:macro>


        <xacro:arm_link prefix="forearm" color="yellow" />
        <xacro:arm_link prefix="hand" color="orange" />


        <joint name="arm_base_joint" type="fixed">
            <parent link="${parent_link}" />
            <child link="arm_base_link" />
            <origin xyz="${ox} 0 ${oz}" rpy="0 0 0"/>
        </joint>

        <joint name="arm_base_forearm_joint" type="revolute">
            <parent link="arm_base_link" />
            <child link="forearm_link" />
            <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
            <axis xyz="0 1 0"/>

            <dynamics damping="0.1" friction="0.05"/>
            <limit effort="100" velocity="100" lower="0.0" upper="${pi/2}" />
        </joint>

        <joint name="forearm_hand_joint" type="revolute">
            <parent link="forearm_link" />
            <child link="hand_link" />
            <origin xyz="0 0 ${arm_torso_length}" rpy="0 0 0" />
            <axis xyz="0 1 0"/>

            <dynamics damping="0.1" friction="0.05"/>
            <limit effort="100" velocity="100" lower="0.0" upper="${pi/2}" />
        </joint>
    </xacro:macro>
</robot>